modules:
  - app/androidApp
  - app/desktopApp
  - app/iosApp
  - app/shared
  - app/webApp
  - architecture-layer/data-layer/movie-data
  - architecture-layer/domain-layer/movie-domain
  - architecture-layer/presentation-layer/dashboard
  - architecture-layer/presentation-layer/movie
  - core/designSystem
  - core/navigation
  - core/resources